### ISSUE TITLE
Unable to get icon

### ISSUE THREAD

**Issue by lukasfotog** [HoroTW/RazerBatteryTray#1]
Novice here, finds device but unable to get the icon to display it seems. I have pillow and pystray installed. Running Ubuntu 22.04.1. 

`Found device: Razer DeathAdder V2 Pro (Wireless)
Traceback (most recent call last):
  File "/home/lukas/RazerBatteryTray/./razer_battery_tray.py", line 83, in <module>
    get_icon(100),
  File "/home/lukas/RazerBatteryTray/./razer_battery_tray.py", line 56, in get_icon
    pil_icon = pil_icon.resize(scale, PIL.Image.Resampling.LANCZOS)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'`

**Comment by HoroTW** [comment]
Hey there,
we will work this out :relaxed: 
It seems that your installed version of Pillow is not compatible - I will do some testing and patch the app
I guess I will do it today in the evening :smile: 

Thanks for reporting!

**Comment by HoroTW** [comment]
Could you send me what version of Pillow you have?

Something like 
```
pip list | grep -i pil
```

**Comment by lukasfotog** [comment]
No problem this exactly what I have been looking for so long lol. Pip version installed is 9.0.1. Looking forward to getting it running!!

**Comment by HoroTW** [comment]
So I added support for older Pillow versions.
So it should be fixed - pull the newest main version and please report back if it works :smile:

**Comment by lukasfotog** [comment]
You are a legend!! Got it working now, this is exactly what I needed. Now just have to learn how to run this on start up ahah
