### ISSUE TITLE
Problem with the setup under NixOS

### ISSUE THREAD

**Issue by HoroTW** [HoroTW/RazerBatteryTray#2]
Soo,
since a friend uses NixOS on his desktop and the client setup there is not as straight forward I'm trying to get it running.

**Comment by HoroTW** [comment]
Hey @x3raX, some idea what else should be said?
Do you want to package it as a nix package?

Anyway, I hope it works now!
Cheers :smile:

**Comment by x3rAx** [comment]
Hi, thanks for looking into this!

I can execute the script now but my terminal is flooded with the following error and I don't see a tray icon:

```
(razer_battery_tray.py:803716): Gtk-CRITICAL **: 23:58:14.311: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

**OS**: NixOS 22.05 (Quokka) x86_64, 22.05.3935.b3a8f7ed267 
**Host**: Framework FRANMACP06 
**Kernel**: 6.0.5 
**Resolution**: 2256x1504, 1920x1080 
**DE**: GNOME 42.4 (Wayland) 
**WM**: Mutter 
**WM Theme**: Adwaita 
**Theme**: Adwaita-dark [GTK2/3] 
**Icons**: Adwaita [GTK2/3] 
**CPU**: 12th Gen Intel i7-1260P (16) @ 4.700GHz 
**GPU**: Intel Device 46a6 
**Nix Version**: nix-env (Nix) 2.8.1
**Nix Channels(root)**: "nixos-22.05"
**Nix Channels(x3ro)**: "home-manager-22.05.tar.gz, n-22.05, nu"

**Comment by HoroTW** [comment]
Hi,
I could identify the issue see https://github.com/HoroTW/RazerBatteryTray/issues/4 .
It is also already resolved - look into the issue and the commit that closed it.
But to repeat the main takeaways:
You need to add:
```nix
environment.systemPackages = [
    pkgs.gnomeExtensions.appindicator
  ];
```
Then you need to manually enable the extension `AppIndicator and KStatusNotifierItem Support` in the `extensions` app.
Then it will work :smile:
