### ISSUE TITLE
Gtk-CRITICAL gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by HoroTW** [HoroTW/RazerBatteryTray#4]
As I found out this happens if you are under WAYLAND and use GNOME and no AppIndicator support is there.
It is fixed by adding an Extension to GNOME.
After installing https://github.com/ubuntu/gnome-shell-extension-appindicator one has to log out and back in again and then manually activate the extension in the `extensions` app.

**Comment by Aasikki** [comment]
Gnome-shell-extension-appindicator not available for fedora 37 :(

**Comment by HoroTW** [comment]
Hello there,
This is the Gnome extensions page - https://extensions.gnome.org/extension/615/appindicator-support/
What version of the gnome shell do you have?
I'm not very familiar with Fedora - doesn't it just have the normal Gnome shell?
Please explain, then we can look at it further. (Maybe I will have to check on a VM)

We will get it sorted out :)
