### ISSUE TITLE
Icon path when using symblink of script

### ISSUE THREAD

**Issue by TriMoon** [HoroTW/RazerBatteryTray#6]
Thanks for this great script :+1: 

It would be great if the script could autodetect if it was called using a symbolic link, so it can find the icons in the directory of the actual script.

To check see the output of `Path of the icons` when doing:
```console
ln -sfr ~/git/RazerBatteryTray/razer_battery_tray.py ~/.local/bin/razer-battery-icon
razer-battery-icon
```

**Comment by HoroTW** [comment]
Hi,
Sorry for the late reply - I will look into that and keep you updated.

**Comment by HoroTW** [comment]
I am happy to report that Python makes it very easy for me 😊.
Functionality was added.
Thanks for your contribution! :slightly_smiling_face:
If anything else bothers you, just open a new issue
